version: "3"
services:
  5gv-message-broker:
    container_name: 5gv-message-broker
    image: 5gv-message-broker:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    command:
      - "--store"
      - "FILE"
      - "--dir"
      - "/data/msg"
    volumes:
      - ../5gv-message-broker/data:/data
    networks:
      vpcbr:
        ipv4_address: 172.23.0.2

  5gv-state-db:
    image: mongo:latest
    container_name: 5gv-state-db
    environment:
      - MONGO_INITDB_DATABASE=state-db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    volumes:
      - 5gv-state-db_data_container:/data/db
    networks:
      vpcbr:
        ipv4_address: 172.23.0.8

  5gv-state-api:
    container_name: 5gv-state-api
    image: 5gv-state-api
    volumes:
      - ../5gv-state-api:/usr/state-api
      - /usr/state-api/node_modules
    command: [npm, "run", "start:dev"]
    depends_on:
      - 5gv-state-db
    ports:
      - 3000:3000
    networks:
      vpcbr:
        ipv4_address: 172.23.0.9

  5gv-cache:
    container_name: 5gv-cache
    image: 5gv-cache:latest
    ports:
      - "8080:8080"
    volumes:
      - ../5gv-cache/cache:/data/cache
      - ../5gv-cache/www:/data/www:ro
      - ../5gv-cache/conf:/etc/nginx:ro
    command: [nginx-debug, "-g", "daemon off;"]
    networks:
      vpcbr:
        ipv4_address: 172.23.0.3
        aliases:
          - "cache.cache"

  5gv-cache-monitor:
    container_name: 5gv-cache-monitor
    image: 5gv-cache-monitor:latest
    ports:
      - "3002:3002"
    volumes:
      - ../5gv-cache-monitor:/usr/monitor
      - /usr/monitor/node_modules
      - ../5gv-cache/cache:/data/cache
    command: [npm, "run", "start:dev"]
    depends_on:
      - 5gv-message-broker
      - 5gv-cache
      - 5gv-state-api
    networks:
      vpcbr:
        ipv4_address: 172.23.0.4

  5gv-aggregator:
    container_name: 5gv-aggregator
    image: 5gv-aggregator:latest
    volumes:
      - ../5gv-aggregator:/usr/aggregator
      - /usr/aggregator/node_modules
    command: [npm, "run", "start:dev"]
    depends_on:
      - 5gv-message-broker
      - 5gv-state-api
    networks:
      vpcbr:
        ipv4_address: 172.23.0.5

  5gv-prefetcher:
    container_name: 5gv-prefetcher
    image: 5gv-prefetcher:latest
    volumes:
      - ../5gv-prefetcher:/usr/prefetcher
      - /usr/prefetcher/node_modules
    command: [npm, "run", "start:dev"]
    depends_on:
      - 5gv-message-broker
      - 5gv-cache
      - 5gv-state-api
    extra_hosts:
      cache: 172.23.0.3
    networks:
      vpcbr:
        ipv4_address: 172.23.0.6
    dns: 172.23.0.12

  5gv-configurator-ui:
    container_name: 5gv-configurator-ui
    image: 5gv-configurator-ui:latest
    ports:
      - "4200:4200"
    volumes:
      - ../5gv-configurator-ui:/usr/configurator-ui
      - /usr/configurator-ui/node_modules
      - /usr/configurator-ui/dist
    command: [ng, "serve", "--host", "0.0.0.0"]
    depends_on:
      - 5gv-aggregator
    networks:
      vpcbr:
        ipv4_address: 172.23.0.7

  5gv-train-resolver:
    container_name: 5gv-train-resolver
    image: 5gv-train-resolver
    ports:
      - "3003:3003"
    volumes:
      - ../5gv-train-resolver:/usr/train-resolver
      - /usr/train-resolver/node_modules
    command: [npm, "run", "start:dev"]
    depends_on:
      - 5gv-cache
    networks:
      vpcbr:
        ipv4_address: 172.23.0.10

  5gv-manifest-transformer:
    container_name: 5gv-manifest-transformer
    image: 5gv-manifest-transformer
    ports:
      - "3004:3004"
    volumes:
      - ../5gv-manifest-transformer:/usr/manifest-transformer
      - /usr/manifest-transformer/node_modules
    command: [npm, "run", "start:dev"]
    depends_on:
      - 5gv-cache
    networks:
      vpcbr:
        ipv4_address: 172.23.0.11

  # Needed to resolve *.cache
  # DNS of default network can not resolve wildcard hostnames
  dns:
    container_name: dns
    restart: always
    image: strm/dnsmasq
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
    cap_add:
      - NET_ADMIN
    networks:
      vpcbr:
        ipv4_address: 172.23.0.12
    expose:
      - 53

volumes:
  5gv-state-db_data_container:

# Custom network needed so we can assign a static IP address to DNS
networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/16
